Feature/12 custom field dans les comptes utilisateurs
ABC-TransitionBasCarbone/clickson-api pull request #22
Opened 2024-08-13 15:04 UTC by RomainCrevecoeur

2024-08-14 08:41 UTC, RomainCrevecoeur commented
Salut @khalilelhazmiri est ce que tu peux review cette PR ?

Merci

2024-08-15 11:00 UTC, khalilelhazmiri requested changes

2024-08-15 11:00 UTC, khalilelhazmiri commented on api/common.ts
> +    return res.status(500).json({ error: 'Internal Server Error' });
Il faut remplacer cette fonctions par: 

`function handleErrors(next: any, error: any) {
  console.error('Fetch error:', error);
  next(error)
}`

pour éviter le problème d'arrêt du serveur une fois il y une erreur, ensuite passer next comme paramètre pour tous les fonctions

2024-08-19 07:29 UTC, RomainCrevecoeur commented on api/common.ts
> +    return res.status(500).json({ error: 'Internal Server Error' });
Oui bonne idée cela va enlever l'erreur de statut 500.
Par contre est ce que je peux faire  
`export function handleErrors(next: any, error: any) {
    console.error('Fetch error:', error);
    next(error)
    return error.status(500).json({ error: 'Internal Server Error' });
}`

Sinon j'ai cette erreur de type :
![image](https://github.com/user-attachments/assets/d57702d7-b510-43c6-9c4c-c9dc8454c5ec)

2024-08-19 14:53 UTC, RomainCrevecoeur commented on api/endpoints/auth.ts
> +
C'est quand je fais un retour en erreur j'ai un retour void au lieu d'un JSON @khalilelhazmiri

2024-08-19 16:31 UTC, khalilelhazmiri commented on api/common.ts
> +    return res.status(500).json({ error: 'Internal Server Error' });
> Par contre est ce que je peux faire ?
export function handleErrors(next: any, error: any) { console.error('Fetch error:', error); next(error) return error.status(500).json({ error: 'Internal Server Error' }); }

pour celui là je peux pas voir car la dernière fois j'avais un problème d'arrête du serveur dès qu'il y a une exception, c'est quoi le nouveau wordpress api pour l'api rest ?

et pour résoudre l'erreur de type: il faut ajouter le type à coté {users} j'ai mis any et j'ai plus d'erreur, aussi il faut passer next avec req et res pour tous les fonctions, ensuite passer next à handleErrors

2024-08-21 08:37 UTC, RomainCrevecoeur commented on api/common.ts
> +    return res.status(500).json({ error: 'Internal Server Error' });
C'est corrigé

2024-08-22 09:18 UTC, khalilelhazmiri approved these changes
Ok pour moi

2024-08-22 09:23 UTC, merged