feat(api): fetch, insert and delete energy and emission data
ABC-TransitionBasCarbone/clickson-api pull request #28
Opened 2024-08-22 14:19 UTC by eaitezouine

2024-08-22 14:22 UTC, khalilelhazmiri requested changes
il faut faire un rebase sur develop car la structure du projet clickson-api est changée

2024-08-26 09:39 UTC, RomainCrevecoeur reviewed
- [ ] Est ce que tu peux faire un rebase de develop pour prendre la nouvel infrastructure avec les endpoints ? Cela permettra d'éviter les conflits pendant le merge

2024-08-26 12:17 UTC, eaitezouine reviewed
done

2024-08-26 12:46 UTC, RomainCrevecoeur approved these changes
Bien joué !

2024-08-27 09:49 UTC, RomainCrevecoeur commented
> done

@khalilelhazmiri est ce que tu peux valider de ton côté ?

2024-08-27 09:53 UTC, khalilelhazmiri approved these changes

2024-08-27 09:53 UTC, khalilelhazmiri commented
Ok pour moi, @eaitezouine tu peux merger

2024-08-27 12:35 UTC, merged