Feature/25 faire des tests unitaires
ABC-TransitionBasCarbone/clickson-api pull request #30
Opened 2024-08-26 09:44 UTC by RomainCrevecoeur

2024-08-27 09:59 UTC, khalilelhazmiri requested changes

2024-08-27 09:59 UTC, khalilelhazmiri commented on api/endpoints/auth.ts
> +    app.delete("/delete-user", async (req: Request, res: Response) => {
Il ne faut pas supprimer le paramètre next car on va rencontrer le problème d'arrêt du serveur une fois une erreur est déclenché

2024-08-27 09:59 UTC, khalilelhazmiri commented on api/endpoints/auth.ts
> +            return handleErrors(error, res);
la fonction handleErrors comprends 2 paramètres: next et error et pas error et res

2024-08-27 09:59 UTC, khalilelhazmiri commented on api/endpoints/auth.ts
> +    app.post('/auth/login', async (req: Request, res: Response) => {
il faut passer le param next pour tous les fonctions

2024-08-27 12:06 UTC, RomainCrevecoeur commented
J'ai fait un rebase et un fix @khalilelhazmiri Est ce que tu peux valider ?

2024-08-27 14:47 UTC, khalilelhazmiri approved these changes
Ok pour moi, tu peux merger

2024-08-27 14:49 UTC, khalilelhazmiri commented
@RomainCrevecoeur avant de merger il faut refaire un rebase avec develop, car il y a des conflits sur le fichier postgres.ts, @eaitezouine a mergé sa branche ce matin

2024-08-27 14:49 UTC, khalilelhazmiri requested changes
@RomainCrevecoeur avant de merger il faut refaire un rebase avec develop, car il y a des conflits sur le fichier postgres.ts, @eaitezouine a mergé sa branche ce matin

2024-08-29 09:03 UTC, khalilelhazmiri approved these changes
@RomainCrevecoeur Ok pour moi, tu peux mergé

2024-08-29 09:15 UTC, merged